name: erlab
channels:
  - conda-forge
dependencies:
  - h5netcdf>=1.2.0
  - igor2>=0.5.6
  - ipykernel
  - joblib>=1.3.2
  - lmfit>=1.2.0,!=1.3.0
  - matplotlib>=3.8.0
  - numba>=0.59.0
  - numbagg>=0.8.1
  - numpy>=1.26.0
  - pip>=19.3
  - pyperclip>=1.8.2
  - pyqtgraph>=0.13.1
  - pyside6>=6.7.0
  - python>=3.11
  - qtawesome>=1.3.1
  - qtpy>=2.4.1
  - scipy>=1.12.0
  - tqdm>=4.66.2
  - uncertainties>=3.1.4
  - varname>=0.13.0
  - xarray>=2024.05.0
