name: erlabrtd
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip>=19.3
  - ipykernel
  - numpy>=1.22.0
  - matplotlib>=3.8.0
  - hvplot
  - xarray
  - h5netcdf
  - varname
  - numba>=0.56.2
  - numbagg
  - numba-progress
  - joblib
  - lmfit>=1.2.0
  - pyqtgraph>=0.13.1
  - tqdm
  - uncertainties>=3.0.1
  - qtawesome
  - superqt
  - qtpy
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxcontrib-bibtex
  - pybtex
  - nbsphinx
  - furo
  - sphinx-design
  - pyperclip
  - pip:
    - pyqt6>=6.2.2
    - csaps
    - igor2 @ git+https://github.com/kmnhan/igor2@master
    - arpes @ git+https://github.com/kmnhan/arpes@master
    - -e git+https://github.com/kmnhan/erlabpy.git#egg=erlab
    - sphinx-qt-documentation
